highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 4
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://DiproMondal.github.io/vitae
author: Dipro Mondal

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Dipro Mondal's Resume
name: Dipro Mondal
email_full: mailto:dipro.mondal12ms@gmail.com
website: github.io/dipro
website_full: https://jekyller.github.io/dipro
github: trending
tel: +31 683920381
tel_full: tel:+31 683920381
google_maps: 'https://www.google.com/maps/dir/52.1636883,4.502345/Herensingel+7A,+2316+JS+Leiden,+Netherlands'
address:
  street: 7A Herensignel
  postcode: 2316 JS
  city: Leiden
  country: the Netherlands
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
